routes/web.php
<?php

use Illuminate\Support\Facades\Route;

/*
|--------------------------------------------------------------------------
| Web Routes
|--------------------------------------------------------------------------
|
| Here is where you can register web routes for your application. These
| routes are loaded by the RouteServiceProvider within a group which
| contains the "web" middleware group. Now create something great!
|
*/

/*Route::get('/', function () {
    return view('welcome');
});*/

Auth::routes();

Route::resource('users', \App\Http\Controllers\UserController::class);

Route::put('/users/{user}/status', ['uses' => 'App\Http\Controllers\UserController@status', 'as' => 'users.status']);

Route::get('/user/ubah-password', ['uses' => 'App\Http\Controllers\UserController@ubahPassword', 'as' => 'users.ubah-password']);

Route::put('/user/ubah-password-proses', ['uses' => 'App\Http\Controllers\UserController@ubahPasswordProses', 'as' => 'users.ubah-password-proses']);

Route::resource('bidang-usaha', \App\Http\Controllers\BidangUsahaController::class);

Route::resource('jenis-barang', \App\Http\Controllers\JenisBarangController::class);

Route::get('/jenis-barangs/get-komoditi-by-jenis-barang', ['uses' => 'App\Http\Controllers\JenisBarangController@getKomoditiByJenisBarang', 'as' => 'jenis-barang.get-komoditi-by-jenis-barang']);

Route::resource('satuan', \App\Http\Controllers\SatuanController::class);

Route::resource('perusahaan', \App\Http\Controllers\PerusahaanController::class);

Route::get('/perusahaans/all', ['uses' => 'App\Http\Controllers\PerusahaanController@all', 'as' => 'perusahaan.all']);

Route::resource('sumber-pembelian', \App\Http\Controllers\SumberPembelianController::class);

Route::resource('lokasi-pembelian', \App\Http\Controllers\LokasiPembelianController::class);

Route::resource('konsumen', \App\Http\Controllers\KonsumenController::class);

Route::resource('asal-konsumen', \App\Http\Controllers\AsalKonsumenController::class);

Route::resource('distribusi-bapokting', \App\Http\Controllers\DistribusiBapoktingController::class);

Route::get('/distribusi-bapokting/{distribusi_bapokting}/aktivitas', ['uses' => 'App\Http\Controllers\DistribusiBapoktingController@aktivitas', 'as' => 'distribusi-bapokting.aktivitas']);

Route::get('/distribusi-bapoktings/cek-data-sama', ['uses' => 'App\Http\Controllers\DistribusiBapoktingController@cekDataSama', 'as' => 'distribusi-bapokting.cek-data-sama']);

Route::resource('pengadaan', \App\Http\Controllers\PengadaanController::class);

Route::resource('pemasaran', \App\Http\Controllers\PemasaranController::class);

Route::resource('slider', \App\Http\Controllers\SliderController::class);

Route::get('/kelurahan/by-kecamatan', ['uses' => 'App\Http\Controllers\KelurahanController@showByKecamatan', 'as' => 'kelurahan.by-kecamatan']);

Route::get('/', [App\Http\Controllers\HomeController::class, 'index'])->name('home');
Route::get('/home', [App\Http\Controllers\HomeController::class, 'index'])->name('home');

Route::get('/home/grafik-status-kepemilikan-toko-per-komoditi', [App\Http\Controllers\HomeController::class, 'showGrafikStatusKepemilikanTokoPerKomoditi'])->name('home.grafik-status-kepemilikan-toko-per-komoditi');

Route::get('/home/grafik-skala-usaha-per-komoditi', [App\Http\Controllers\HomeController::class, 'showGrafikSkalaUsahaPerKomoditi'])->name('home.grafik-skala-usaha-per-komoditi');

Route::get('/home/grafik-pengadaan-by-sumber-pembelian-per-komoditi', [App\Http\Controllers\HomeController::class, 'showGrafikPengadaanBySumberPembelianPerKomoditi'])->name('home.grafik-pengadaan-by-sumber-pembelian-per-komoditi');

Route::get('/home/grafik-pengadaan-by-lokasi-pembelian-per-komoditi', [App\Http\Controllers\HomeController::class, 'showGrafikPengadaanByLokasiPembelianPerKomoditi'])->name('home.grafik-pengadaan-by-lokasi-pembelian-per-komoditi');

Route::get('/home/grafik-pemasaran-by-konsumen-per-komoditi', [App\Http\Controllers\HomeController::class, 'showGrafikPemasaranByKonsumenPerKomoditi'])->name('home.grafik-pemasaran-by-konsumen-per-komoditi');

Route::get('/home/grafik-pemasaran-by-asal-konsumen-per-komoditi', [App\Http\Controllers\HomeController::class, 'showGrafikPemasaranByAsalKonsumenPerKomoditi'])->name('home.grafik-pemasaran-by-asal-konsumen-per-komoditi');

Route::get('/home/grafik-pengadaan-per-komoditi-detail', [App\Http\Controllers\HomeController::class, 'showGrafikPengadaanPerKomoditiDetail'])->name('home.grafik-pengadaan-per-komoditi-detail');

Route::get('/home/grafik-pemasaran-per-komoditi-detail', [App\Http\Controllers\HomeController::class, 'showGrafikPemasaranPerKomoditiDetail'])->name('home.grafik-pemasaran-per-komoditi-detail');

Route::get('/home/grafik-jenis-kelamin-pedagang-per-komoditi-detail', [App\Http\Controllers\HomeController::class, 'showGrafikJenisKelaminPedagangPerKomoditiDetail'])->name('home.grafik-jenis-kelamin-pedagang-per-komoditi-detail');

Route::get('/home/grafik-rerata-lama-usaha-per-komoditi-detail', [App\Http\Controllers\HomeController::class, 'showGrafikRerataLamaUsahaPerKomoditiDetail'])->name('home.grafik-rerata-lama-usaha-per-komoditi-detail');

Route::get('/home/grafik-status-kepemilikan-toko-per-komoditi-detail', [App\Http\Controllers\HomeController::class, 'showGrafikStatusKepemilikanTokoPerKomoditiDetail'])->name('home.grafik-status-kepemilikan-toko-per-komoditi-detail');

Route::get('/home/grafik-skala-usaha-per-komoditi-detail', [App\Http\Controllers\HomeController::class, 'showGrafikSkalaUsahaPerKomoditiDetail'])->name('home.grafik-skala-usaha-per-komoditi-detail');

Route::get('/home/grafik-pengadaan-by-sumber-pembelian-per-komoditi-detail', [App\Http\Controllers\HomeController::class, 'showGrafikPengadaanBySumberPembelianPerKomoditiDetail'])->name('home.grafik-pengadaan-by-sumber-pembelian-per-komoditi-detail');

Route::get('/home/grafik-pengadaan-by-lokasi-pembelian-per-komoditi-detail', [App\Http\Controllers\HomeController::class, 'showGrafikPengadaanByLokasiPembelianPerKomoditiDetail'])->name('home.grafik-pengadaan-by-lokasi-pembelian-per-komoditi-detail');

Route::get('/home/grafik-pemasaran-by-konsumen-per-komoditi-detail', [App\Http\Controllers\HomeController::class, 'showGrafikPemasaranByKonsumenPerKomoditiDetail'])->name('home.grafik-pemasaran-by-konsumen-per-komoditi-detail');

Route::get('/home/grafik-pemasaran-by-asal-konsumen-per-komoditi-detail', [App\Http\Controllers\HomeController::class, 'showGrafikPemasaranByAsalKonsumenPerKomoditiDetail'])->name('home.grafik-pemasaran-by-asal-konsumen-per-komoditi-detail');

Route::get('/home/map-koordinat-perusahaan', [App\Http\Controllers\HomeController::class, 'getPerusahaanByFilter'])->name('home.map-koordinat-perusahaan');

Route::get('/home/tabel-perusahaan', [App\Http\Controllers\HomeController::class, 'getPerusahaanByFilter'])->name('home.tabel-perusahaan');

Route::get('/home/tabel-stok-barang', [App\Http\Controllers\HomeController::class, 'getStokByJenisBarang'])->name('home.tabel-stok-barang');

Route::get('/home/grafik-jenis-kelamin-pedagang-by-jenis-produk', [App\Http\Controllers\HomeController::class, 'showGrafikJenisKelaminPedagangByJenisProduk'])->name('home.grafik-jenis-kelamin-pedagang-by-jenis-produk');

app/Models/JenisBarang.php
<?php
/**
 * Created by PhpStorm.
 * User: rizky
 * Date: 09/09/2021
 * Time: 11:53
 */

namespace App\Models;

use Illuminate\Database\Eloquent\Model;
use Illuminate\Database\Eloquent\SoftDeletes;

class JenisBarang extends Model
{
    use SoftDeletes;

    protected $table = 'jenis_barang';

    protected $fillable = [
        'kode_jenis_barang',
        'id_bidang_usaha',
        'nama_barang',
        'user_create',
        'user_update',
        'user_delete',
    ];
}

app/Models/JenisBarangView.php
<?php
/**
 * Created by PhpStorm.
 * User: rizky
 * Date: 09/09/2021
 * Time: 14:15
 */

namespace App\Models;

use Illuminate\Database\Eloquent\Model;

class JenisBarangView extends Model
{
    protected $table = 'view_jenis_barang';
}

app/Http/Controllers/JenisBarangController.php
<?php
/**
 * Created by PhpStorm.
 * User: rizki
 * Date: 31/08/2021
 * Time: 4:27
 */

namespace App\Http\Controllers;

use Illuminate\Http\Request;
use App\Models\JenisBarang;
use App\Models\JenisBarangView;
use App\Models\BidangUsaha;

class JenisBarangController extends Controller
{
    function __construct()
    {
        $this->middleware('auth');
    }

    public function index()
    {
        $jenisBarang = JenisBarangView::all();
        return view('jenis_barang.index', [
            'jenis_barang' => $jenisBarang
        ]);
    }

    private function form()
    {
        $bidang_usaha = BidangUsaha::all();

        return [
            'bidang_usaha' => $bidang_usaha,
        ];
    }

    public function create()
    {
        $data = [];
        $form = $this->form();

        return view('jenis_barang.create', array_merge($data, $form));
    }

    public function store(Request $request)
    {
        $request->validate([
            'nama_barang' => 'required',
            'id_bidang_usaha' => 'required',
        ]);

        $array = $request->only([
            'id_bidang_usaha', 'nama_barang'
        ]);
        $kode_jenis_barang = kode_hash();

        $array['kode_jenis_barang'] = $kode_jenis_barang;
        $array['user_create'] = $request->user()->id;

        $jenis_barang = JenisBarang::create($array);

        return redirect()->route('jenis-barang.index')
            ->with('success_message', 'Berhasil menambah jenis barang baru.');

    }

    public function show($id)
    {
        //
    }

    public function edit($id)
    {
        $jenis_barang = JenisBarang::find($id);

        if (!$jenis_barang) return redirect()->route('jenis-barang.index')
            ->with('error_message', 'Jenis barang dengan ID: '.$id.' tidak ditemukan.');

        $data = ['jenis_barang' => $jenis_barang];
        $form = $this->form();

        return view('jenis_barang.edit', array_merge($data, $form));
    }

    public function update(Request $request, $id)
    {
        $request->validate([
            'nama_barang' => 'required',
            'id_bidang_usaha' => 'required',
        ]);

        $jenis_barang = JenisBarang::find($id);

        $jenis_barang->nama_barang = $request->nama_barang;
        $jenis_barang->id_bidang_usaha = $request->id_bidang_usaha;
        $jenis_barang->user_update = $request->user()->id;

        $jenis_barang->save();

        return redirect()->route('jenis-barang.index')
            ->with('success_message', 'Berhasil mengubah jenis barang.');
    }

    public function destroy(Request $request, $id)
    {
        $jenis_barang = JenisBarang::find($id);

        if ($jenis_barang) {
            $jenis_barang->user_delete = $request->user()->id;

            $jenis_barang->save();

            $jenis_barang->delete();
        }

        return redirect()->route('jenis-barang.index')
            ->with('success_message', 'Berhasil menghapus jenis barang.');
    }

    public function getKomoditiByJenisBarang(Request $request)
    {
        $jenis_barang = $request->jenis_barang;

        $getKomoditi = JenisBarangView::where(['jenis_barang' => $jenis_barang])->get();

        return response()->json([
            'jenis_barang' => $getKomoditi,
        ]);
    }
}

resources/views/jenis_barang/create.blade.php
<?php
/**
 * Created by PhpStorm.
 * User: rizki
 * Date: 31/08/2021
 * Time: 4:33
 */

$title = 'Tambah Jenis Barang';

?>

@extends('adminlte::page')

@section('title', $title)

@section('content_header')
    <h1 class="m-0 text-dark">{{ $title }}</h1>
@stop

@section('content')
    @include('layouts/flash-message')

    <form action="{{route('jenis-barang.store')}}" method="post">
        @csrf
        @include('jenis_barang/form')
    </form>
@stop

resources/views/jenis_barang/edit.blade.php
<?php
/**
 * Created by PhpStorm.
 * User: rizky
 * Date: 09/09/2021
 * Time: 14:21
 */

$title = 'Edit Jenis Barang';

?>

@extends('adminlte::page')

@section('title', $title)

@section('content_header')
    <h1 class="m-0 text-dark">{{ $title }}</h1>
@stop

@section('content')
    @include('layouts/flash-message')

    <form action="{{route('jenis-barang.update', $jenis_barang)}}" method="post">
        @method('PUT')
        @csrf
        @include('jenis_barang/form');
    </form>
@stop

resources/views/jenis_barang/form.blade.php
<?php
/**
 * Created by PhpStorm.
 * User: rizky
 * Date: 09/09/2021
 * Time: 12:00
 */

?>

<div class="row">
    <div class="col-12">
        <div class="card">
            <div class="card-body">
                <div class="form-group">
                    <label for="nama_barang">Nama Barang</label>
                    <input type="text" class="form-control @error('nama_barang') is-invalid @enderror" id="nama_barang" placeholder="Nama Barang" name="nama_barang" value="{{ isset($jenis_barang)? $jenis_barang->nama_barang : old('nama_barang') }}" required>
                    @error('nama_barang') <span class="text-danger">{{$message}}</span> @enderror
                </div>

                <div class="form-group">
                    <label for="id_bidang_usaha">KBLI</label>
                    <select class="form-control @error('id_bidang_usaha') is-invalid @enderror" id="id_bidang_usaha" name="id_bidang_usaha" required>
                        <option value="">-- Pilih KBLI --</option>
                        @foreach($bidang_usaha as $row)
                            <option value="{{ $row->id }}" {{ (isset($jenis_barang) && $jenis_barang->id_bidang_usaha == $row->id || old('id_bidang_usaha') == $row->id)? 'selected' : old('id_bidang_usaha') }}>{{ $row->kode_kbli }} - {{ $row->nama_kbli }}</option>
                        @endforeach
                    </select>
                    @error('id_bidang_usaha') <span class="text-danger">{{ $message }}</span> @enderror
                </div>
            </div>

            <div class="card-footer">
                {!! button_save() !!}
                {!! button_cancel('jenis-barang') !!}
            </div>
        </div>
    </div>
</div>

resources/views/jenis_barang/index.blade.php
<?php
/**
 * Created by PhpStorm.
 * User: rizki
 * Date: 31/08/2021
 * Time: 4:29
 */

$title = 'Pengelolaan Data Jenis Barang';

?>

@extends('adminlte::page')

@section('title', $title)

@section('content_header')
    <h1 class="m-0 text-dark">{{ $title }}</h1>
@stop

@section('content')
    @include('layouts/flash-message')

    <div class="row">
        <div class="col-12">
            <div class="card">
                <div class="card-header">
                    {!! button_add('jenis-barang') !!}
                </div>
                <div class="card-body">
                    <table class="table table-hover table-bordered table-stripped" id="simpleDatatable">
                        <thead>
                        <tr>
                            <th>No.</th>
                            <th>Nama Barang</th>
                            <th>KBLI</th>
                            <th>Jenis Barang</th>
                            <th class="text-center">Opsi</th>
                        </tr>
                        </thead>
                        <tbody>
                        @foreach($jenis_barang as $key => $row)
                            <tr>
                                <td>{{$key+1}}</td>
                                <td>{{$row->nama_barang}}</td>
                                <td>{{$row->kode_kbli}} - {{ $row->nama_kbli }}</td>
                                <td>{{ jenis_barangs()[$row->jenis_barang] }}</td>
                                <td class="text-center">
                                    {!! button_edit('jenis-barang', $row) !!}
                                    {!! button_delete('jenis-barang', $row) !!}
                                </td>
                            </tr>
                        @endforeach
                        </tbody>
                    </table>
                </div>
            </div>
        </div>
    </div>
@stop

@push('js')
    @include('layouts/js')
@endpush