routes/web.php
<?php

use Illuminate\Support\Facades\Route;

/*
|--------------------------------------------------------------------------
| Web Routes
|--------------------------------------------------------------------------
|
| Here is where you can register web routes for your application. These
| routes are loaded by the RouteServiceProvider within a group which
| contains the "web" middleware group. Now create something great!
|
*/

/*Route::get('/', function () {
    return view('welcome');
});*/

Auth::routes();

Route::resource('users', \App\Http\Controllers\UserController::class);

Route::put('/users/{user}/status', ['uses' => 'App\Http\Controllers\UserController@status', 'as' => 'users.status']);

Route::get('/user/ubah-password', ['uses' => 'App\Http\Controllers\UserController@ubahPassword', 'as' => 'users.ubah-password']);

Route::put('/user/ubah-password-proses', ['uses' => 'App\Http\Controllers\UserController@ubahPasswordProses', 'as' => 'users.ubah-password-proses']);

Route::resource('bidang-usaha', \App\Http\Controllers\BidangUsahaController::class);

Route::resource('jenis-barang', \App\Http\Controllers\JenisBarangController::class);

Route::get('/jenis-barangs/get-komoditi-by-jenis-barang', ['uses' => 'App\Http\Controllers\JenisBarangController@getKomoditiByJenisBarang', 'as' => 'jenis-barang.get-komoditi-by-jenis-barang']);

Route::resource('satuan', \App\Http\Controllers\SatuanController::class);

Route::resource('perusahaan', \App\Http\Controllers\PerusahaanController::class);

Route::get('/perusahaans/all', ['uses' => 'App\Http\Controllers\PerusahaanController@all', 'as' => 'perusahaan.all']);

Route::resource('sumber-pembelian', \App\Http\Controllers\SumberPembelianController::class);

Route::resource('lokasi-pembelian', \App\Http\Controllers\LokasiPembelianController::class);

Route::resource('konsumen', \App\Http\Controllers\KonsumenController::class);

Route::resource('asal-konsumen', \App\Http\Controllers\AsalKonsumenController::class);

Route::resource('distribusi-bapokting', \App\Http\Controllers\DistribusiBapoktingController::class);

Route::get('/distribusi-bapokting/{distribusi_bapokting}/aktivitas', ['uses' => 'App\Http\Controllers\DistribusiBapoktingController@aktivitas', 'as' => 'distribusi-bapokting.aktivitas']);

Route::get('/distribusi-bapoktings/cek-data-sama', ['uses' => 'App\Http\Controllers\DistribusiBapoktingController@cekDataSama', 'as' => 'distribusi-bapokting.cek-data-sama']);

Route::resource('pengadaan', \App\Http\Controllers\PengadaanController::class);

Route::resource('pemasaran', \App\Http\Controllers\PemasaranController::class);

Route::resource('slider', \App\Http\Controllers\SliderController::class);

Route::get('/kelurahan/by-kecamatan', ['uses' => 'App\Http\Controllers\KelurahanController@showByKecamatan', 'as' => 'kelurahan.by-kecamatan']);

Route::get('/', [App\Http\Controllers\HomeController::class, 'index'])->name('home');
Route::get('/home', [App\Http\Controllers\HomeController::class, 'index'])->name('home');

Route::get('/home/grafik-status-kepemilikan-toko-per-komoditi', [App\Http\Controllers\HomeController::class, 'showGrafikStatusKepemilikanTokoPerKomoditi'])->name('home.grafik-status-kepemilikan-toko-per-komoditi');

Route::get('/home/grafik-skala-usaha-per-komoditi', [App\Http\Controllers\HomeController::class, 'showGrafikSkalaUsahaPerKomoditi'])->name('home.grafik-skala-usaha-per-komoditi');

Route::get('/home/grafik-pengadaan-by-sumber-pembelian-per-komoditi', [App\Http\Controllers\HomeController::class, 'showGrafikPengadaanBySumberPembelianPerKomoditi'])->name('home.grafik-pengadaan-by-sumber-pembelian-per-komoditi');

Route::get('/home/grafik-pengadaan-by-lokasi-pembelian-per-komoditi', [App\Http\Controllers\HomeController::class, 'showGrafikPengadaanByLokasiPembelianPerKomoditi'])->name('home.grafik-pengadaan-by-lokasi-pembelian-per-komoditi');

Route::get('/home/grafik-pemasaran-by-konsumen-per-komoditi', [App\Http\Controllers\HomeController::class, 'showGrafikPemasaranByKonsumenPerKomoditi'])->name('home.grafik-pemasaran-by-konsumen-per-komoditi');

Route::get('/home/grafik-pemasaran-by-asal-konsumen-per-komoditi', [App\Http\Controllers\HomeController::class, 'showGrafikPemasaranByAsalKonsumenPerKomoditi'])->name('home.grafik-pemasaran-by-asal-konsumen-per-komoditi');

Route::get('/home/grafik-pengadaan-per-komoditi-detail', [App\Http\Controllers\HomeController::class, 'showGrafikPengadaanPerKomoditiDetail'])->name('home.grafik-pengadaan-per-komoditi-detail');

Route::get('/home/grafik-pemasaran-per-komoditi-detail', [App\Http\Controllers\HomeController::class, 'showGrafikPemasaranPerKomoditiDetail'])->name('home.grafik-pemasaran-per-komoditi-detail');

Route::get('/home/grafik-jenis-kelamin-pedagang-per-komoditi-detail', [App\Http\Controllers\HomeController::class, 'showGrafikJenisKelaminPedagangPerKomoditiDetail'])->name('home.grafik-jenis-kelamin-pedagang-per-komoditi-detail');

Route::get('/home/grafik-rerata-lama-usaha-per-komoditi-detail', [App\Http\Controllers\HomeController::class, 'showGrafikRerataLamaUsahaPerKomoditiDetail'])->name('home.grafik-rerata-lama-usaha-per-komoditi-detail');

Route::get('/home/grafik-status-kepemilikan-toko-per-komoditi-detail', [App\Http\Controllers\HomeController::class, 'showGrafikStatusKepemilikanTokoPerKomoditiDetail'])->name('home.grafik-status-kepemilikan-toko-per-komoditi-detail');

Route::get('/home/grafik-skala-usaha-per-komoditi-detail', [App\Http\Controllers\HomeController::class, 'showGrafikSkalaUsahaPerKomoditiDetail'])->name('home.grafik-skala-usaha-per-komoditi-detail');

Route::get('/home/grafik-pengadaan-by-sumber-pembelian-per-komoditi-detail', [App\Http\Controllers\HomeController::class, 'showGrafikPengadaanBySumberPembelianPerKomoditiDetail'])->name('home.grafik-pengadaan-by-sumber-pembelian-per-komoditi-detail');

Route::get('/home/grafik-pengadaan-by-lokasi-pembelian-per-komoditi-detail', [App\Http\Controllers\HomeController::class, 'showGrafikPengadaanByLokasiPembelianPerKomoditiDetail'])->name('home.grafik-pengadaan-by-lokasi-pembelian-per-komoditi-detail');

Route::get('/home/grafik-pemasaran-by-konsumen-per-komoditi-detail', [App\Http\Controllers\HomeController::class, 'showGrafikPemasaranByKonsumenPerKomoditiDetail'])->name('home.grafik-pemasaran-by-konsumen-per-komoditi-detail');

Route::get('/home/grafik-pemasaran-by-asal-konsumen-per-komoditi-detail', [App\Http\Controllers\HomeController::class, 'showGrafikPemasaranByAsalKonsumenPerKomoditiDetail'])->name('home.grafik-pemasaran-by-asal-konsumen-per-komoditi-detail');

Route::get('/home/map-koordinat-perusahaan', [App\Http\Controllers\HomeController::class, 'getPerusahaanByFilter'])->name('home.map-koordinat-perusahaan');

Route::get('/home/tabel-perusahaan', [App\Http\Controllers\HomeController::class, 'getPerusahaanByFilter'])->name('home.tabel-perusahaan');

Route::get('/home/tabel-stok-barang', [App\Http\Controllers\HomeController::class, 'getStokByJenisBarang'])->name('home.tabel-stok-barang');

Route::get('/home/grafik-jenis-kelamin-pedagang-by-jenis-produk', [App\Http\Controllers\HomeController::class, 'showGrafikJenisKelaminPedagangByJenisProduk'])->name('home.grafik-jenis-kelamin-pedagang-by-jenis-produk');

app/Models/Satuan.php
<?php
/**
 * Created by PhpStorm.
 * User: rizky
 * Date: 09/09/2021
 * Time: 14:31
 */

namespace App\Models;

use Illuminate\Database\Eloquent\Model;
use Illuminate\Database\Eloquent\SoftDeletes;

class Satuan extends Model
{
    use SoftDeletes;

    protected $table = 'satuan';

    protected $fillable = [
        'kode_satuan',
        'satuan',
        'nama_satuan',
        'user_create',
        'user_update',
        'user_delete',
    ];
}

app/Http/Controllers/SatuanController.php
<?php
/**
 * Created by PhpStorm.
 * User: rizki
 * Date: 31/08/2021
 * Time: 4:37
 */

namespace App\Http\Controllers;

Use Illuminate\Http\Request;
Use App\Models\Satuan;

class SatuanController extends Controller
{
    function __construct()
    {
        $this->middleware('auth');
    }

    public function index()
    {
        $satuan = Satuan::all();
        return view('satuan.index', [
            'satuan' => $satuan
        ]);
    }

    public function create()
    {
        return view('satuan.create');
    }

    public function store(Request $request)
    {
        $request->validate([
            'satuan' => 'required|unique:satuan,satuan',
            'nama_satuan' => 'required',
        ]);

        $array = $request->only([
            'satuan', 'nama_satuan'
        ]);
        $kode_satuan = kode_hash();

        $array['kode_satuan'] = $kode_satuan;
        $array['user_create'] = $request->user()->id;

        $satuan = Satuan::create($array);

        return redirect()->route('satuan.index')
            ->with('success_message', 'Berhasil menambah satuan baru.');
    }

    public function show($id)
    {
        //
    }

    public function edit($id)
    {
        $satuan = Satuan::find($id);

        if (!$satuan) return redirect()->route('satuan.index')
            ->with('error_message', 'Satuan dengan ID: '.$id.' tidak ditemukan.');

        return view('satuan.edit', [
            'satuan' => $satuan
        ]);
    }

    public function update(Request $request, $id)
    {
        $request->validate([
            'satuan' => 'required|unique:satuan,satuan,'.$id,
            'nama_satuan' => 'required',
        ]);

        $satuan = Satuan::find($id);

        $satuan->satuan = $request->satuan;
        $satuan->nama_satuan = $request->nama_satuan;
        $satuan->user_update = $request->user()->id;

        $satuan->save();

        return redirect()->route('satuan.index')
            ->with('success_message', 'Berhasil mengubah satuan.');
    }

    public function destroy(Request $request, $id)
    {
        $satuan = Satuan::find($id);

        if ($satuan) {
            $satuan->user_delete = $request->user()->id;

            $satuan->save();

            $satuan->delete();
        }

        return redirect()->route('satuan.index')
            ->with('success_message', 'Berhasil menghapus satuan.');
    }
}

resources/views/satuan/create.blade.php
<?php
/**
 * Created by PhpStorm.
 * User: rizki
 * Date: 31/08/2021
 * Time: 4:41
 */

$title = 'Tambah Satuan';

?>

@extends('adminlte::page')

@section('title', $title)

@section('content_header')
    <h1 class="m-0 text-dark">{{ $title }}</h1>
@stop

@section('content')
    @include('layouts/flash-message')

    <form action="{{route('satuan.store')}}" method="post">
        @csrf
        @include('satuan/form')
    </form>
@stop

resources/views/satuan/edit.blade.php
<?php
/**
 * Created by PhpStorm.
 * User: rizky
 * Date: 09/09/2021
 * Time: 14:49
 */

$title = 'Edit Satuan';

?>

@extends('adminlte::page')

@section('title', $title)

@section('content_header')
    <h1 class="m-0 text-dark">{{ $title }}</h1>
@stop

@section('content')
    @include('layouts/flash-message')

    <form action="{{route('satuan.update', $satuan)}}" method="post">
        @method('PUT')
        @csrf
        @include('satuan/form');
    </form>
@stop

resources/views/satuan/form.blade.php
<?php
/**
 * Created by PhpStorm.
 * User: rizky
 * Date: 09/09/2021
 * Time: 14:39
 */

?>

<div class="row">
    <div class="col-12">
        <div class="card">
            <div class="card-body">
                <div class="form-group">
                    <label for="satuan">Satuan</label>
                    <input type="text" class="form-control @error('satuan') is-invalid @enderror" id="satuan" placeholder="Kg" name="satuan" value="{{ isset($satuan)? $satuan->satuan : old('satuan') }}" required>
                    <span class="form-text text-muted">Contoh: Kg, M, Pack, Pcs</span>
                    @error('satuan') <span class="text-danger">{{$message}}</span> @enderror
                </div>

                <div class="form-group">
                    <label for="nama_satuan">Nama Satuan</label>
                    <input type="text" class="form-control @error('nama_satuan') is-invalid @enderror" id="nama_satuan" placeholder="Kilogram" name="nama_satuan" value="{{ isset($satuan)? $satuan->nama_satuan : old('nama_satuan') }}" required>
                    <span class="form-text text-muted">Contoh: Kilogram, Meter, Pack, Piece</span>
                    @error('nama_satuan') <span class="text-danger">{{$message}}</span> @enderror
                </div>
            </div>

            <div class="card-footer">
                {!! button_save() !!}
                {!! button_cancel('satuan') !!}
            </div>
        </div>
    </div>
</div>

resources/views/satuan/index.blade.php
<?php
/**
 * Created by PhpStorm.
 * User: rizki
 * Date: 31/08/2021
 * Time: 4:39
 */

$title = 'Pengelolaan Data Satuan';

?>

@extends('adminlte::page')

@section('title', $title)

@section('content_header')
    <h1 class="m-0 text-dark">{{ $title }}</h1>
@stop

@section('content')
    @include('layouts/flash-message')

    <div class="row">
        <div class="col-12">
            <div class="card">
                <div class="card-header">
                    {!! button_add('satuan') !!}
                </div>
                <div class="card-body">
                    <table class="table table-hover table-bordered table-stripped" id="simpleDatatable">
                        <thead>
                        <tr>
                            <th>No.</th>
                            <th>Satuan</th>
                            <th>Nama</th>
                            <th class="text-center">Opsi</th>
                        </tr>
                        </thead>
                        <tbody>
                        @foreach($satuan as $key => $row)
                            <tr>
                                <td>{{$key+1}}</td>
                                <td>{{$row->satuan}}</td>
                                <td>{{$row->nama_satuan}}</td>
                                <td class="text-center">
                                    {!! button_edit('satuan', $row) !!}
                                    {!! button_delete('satuan', $row) !!}
                                </td>
                            </tr>
                        @endforeach
                        </tbody>
                    </table>
                </div>
            </div>
        </div>
    </div>
@stop

@push('js')
    @include('layouts/js')
@endpush