routes/web.php
<?php

use Illuminate\Support\Facades\Route;

/*
|--------------------------------------------------------------------------
| Web Routes
|--------------------------------------------------------------------------
|
| Here is where you can register web routes for your application. These
| routes are loaded by the RouteServiceProvider within a group which
| contains the "web" middleware group. Now create something great!
|
*/

/*Route::get('/', function () {
    return view('welcome');
});*/

Auth::routes();

Route::resource('users', \App\Http\Controllers\UserController::class);

Route::put('/users/{user}/status', ['uses' => 'App\Http\Controllers\UserController@status', 'as' => 'users.status']);

Route::get('/user/ubah-password', ['uses' => 'App\Http\Controllers\UserController@ubahPassword', 'as' => 'users.ubah-password']);

Route::put('/user/ubah-password-proses', ['uses' => 'App\Http\Controllers\UserController@ubahPasswordProses', 'as' => 'users.ubah-password-proses']);

Route::resource('bidang-usaha', \App\Http\Controllers\BidangUsahaController::class);

Route::resource('jenis-barang', \App\Http\Controllers\JenisBarangController::class);

Route::get('/jenis-barangs/get-komoditi-by-jenis-barang', ['uses' => 'App\Http\Controllers\JenisBarangController@getKomoditiByJenisBarang', 'as' => 'jenis-barang.get-komoditi-by-jenis-barang']);

Route::resource('satuan', \App\Http\Controllers\SatuanController::class);

Route::resource('perusahaan', \App\Http\Controllers\PerusahaanController::class);

Route::get('/perusahaans/all', ['uses' => 'App\Http\Controllers\PerusahaanController@all', 'as' => 'perusahaan.all']);

Route::resource('sumber-pembelian', \App\Http\Controllers\SumberPembelianController::class);

Route::resource('lokasi-pembelian', \App\Http\Controllers\LokasiPembelianController::class);

Route::resource('konsumen', \App\Http\Controllers\KonsumenController::class);

Route::resource('asal-konsumen', \App\Http\Controllers\AsalKonsumenController::class);

Route::resource('distribusi-bapokting', \App\Http\Controllers\DistribusiBapoktingController::class);

Route::get('/distribusi-bapokting/{distribusi_bapokting}/aktivitas', ['uses' => 'App\Http\Controllers\DistribusiBapoktingController@aktivitas', 'as' => 'distribusi-bapokting.aktivitas']);

Route::get('/distribusi-bapoktings/cek-data-sama', ['uses' => 'App\Http\Controllers\DistribusiBapoktingController@cekDataSama', 'as' => 'distribusi-bapokting.cek-data-sama']);

Route::resource('pengadaan', \App\Http\Controllers\PengadaanController::class);

Route::resource('pemasaran', \App\Http\Controllers\PemasaranController::class);

Route::resource('slider', \App\Http\Controllers\SliderController::class);

Route::get('/kelurahan/by-kecamatan', ['uses' => 'App\Http\Controllers\KelurahanController@showByKecamatan', 'as' => 'kelurahan.by-kecamatan']);

Route::get('/', [App\Http\Controllers\HomeController::class, 'index'])->name('home');
Route::get('/home', [App\Http\Controllers\HomeController::class, 'index'])->name('home');

Route::get('/home/grafik-status-kepemilikan-toko-per-komoditi', [App\Http\Controllers\HomeController::class, 'showGrafikStatusKepemilikanTokoPerKomoditi'])->name('home.grafik-status-kepemilikan-toko-per-komoditi');

Route::get('/home/grafik-skala-usaha-per-komoditi', [App\Http\Controllers\HomeController::class, 'showGrafikSkalaUsahaPerKomoditi'])->name('home.grafik-skala-usaha-per-komoditi');

Route::get('/home/grafik-pengadaan-by-sumber-pembelian-per-komoditi', [App\Http\Controllers\HomeController::class, 'showGrafikPengadaanBySumberPembelianPerKomoditi'])->name('home.grafik-pengadaan-by-sumber-pembelian-per-komoditi');

Route::get('/home/grafik-pengadaan-by-lokasi-pembelian-per-komoditi', [App\Http\Controllers\HomeController::class, 'showGrafikPengadaanByLokasiPembelianPerKomoditi'])->name('home.grafik-pengadaan-by-lokasi-pembelian-per-komoditi');

Route::get('/home/grafik-pemasaran-by-konsumen-per-komoditi', [App\Http\Controllers\HomeController::class, 'showGrafikPemasaranByKonsumenPerKomoditi'])->name('home.grafik-pemasaran-by-konsumen-per-komoditi');

Route::get('/home/grafik-pemasaran-by-asal-konsumen-per-komoditi', [App\Http\Controllers\HomeController::class, 'showGrafikPemasaranByAsalKonsumenPerKomoditi'])->name('home.grafik-pemasaran-by-asal-konsumen-per-komoditi');

Route::get('/home/grafik-pengadaan-per-komoditi-detail', [App\Http\Controllers\HomeController::class, 'showGrafikPengadaanPerKomoditiDetail'])->name('home.grafik-pengadaan-per-komoditi-detail');

Route::get('/home/grafik-pemasaran-per-komoditi-detail', [App\Http\Controllers\HomeController::class, 'showGrafikPemasaranPerKomoditiDetail'])->name('home.grafik-pemasaran-per-komoditi-detail');

Route::get('/home/grafik-jenis-kelamin-pedagang-per-komoditi-detail', [App\Http\Controllers\HomeController::class, 'showGrafikJenisKelaminPedagangPerKomoditiDetail'])->name('home.grafik-jenis-kelamin-pedagang-per-komoditi-detail');

Route::get('/home/grafik-rerata-lama-usaha-per-komoditi-detail', [App\Http\Controllers\HomeController::class, 'showGrafikRerataLamaUsahaPerKomoditiDetail'])->name('home.grafik-rerata-lama-usaha-per-komoditi-detail');

Route::get('/home/grafik-status-kepemilikan-toko-per-komoditi-detail', [App\Http\Controllers\HomeController::class, 'showGrafikStatusKepemilikanTokoPerKomoditiDetail'])->name('home.grafik-status-kepemilikan-toko-per-komoditi-detail');

Route::get('/home/grafik-skala-usaha-per-komoditi-detail', [App\Http\Controllers\HomeController::class, 'showGrafikSkalaUsahaPerKomoditiDetail'])->name('home.grafik-skala-usaha-per-komoditi-detail');

Route::get('/home/grafik-pengadaan-by-sumber-pembelian-per-komoditi-detail', [App\Http\Controllers\HomeController::class, 'showGrafikPengadaanBySumberPembelianPerKomoditiDetail'])->name('home.grafik-pengadaan-by-sumber-pembelian-per-komoditi-detail');

Route::get('/home/grafik-pengadaan-by-lokasi-pembelian-per-komoditi-detail', [App\Http\Controllers\HomeController::class, 'showGrafikPengadaanByLokasiPembelianPerKomoditiDetail'])->name('home.grafik-pengadaan-by-lokasi-pembelian-per-komoditi-detail');

Route::get('/home/grafik-pemasaran-by-konsumen-per-komoditi-detail', [App\Http\Controllers\HomeController::class, 'showGrafikPemasaranByKonsumenPerKomoditiDetail'])->name('home.grafik-pemasaran-by-konsumen-per-komoditi-detail');

Route::get('/home/grafik-pemasaran-by-asal-konsumen-per-komoditi-detail', [App\Http\Controllers\HomeController::class, 'showGrafikPemasaranByAsalKonsumenPerKomoditiDetail'])->name('home.grafik-pemasaran-by-asal-konsumen-per-komoditi-detail');

Route::get('/home/map-koordinat-perusahaan', [App\Http\Controllers\HomeController::class, 'getPerusahaanByFilter'])->name('home.map-koordinat-perusahaan');

Route::get('/home/tabel-perusahaan', [App\Http\Controllers\HomeController::class, 'getPerusahaanByFilter'])->name('home.tabel-perusahaan');

Route::get('/home/tabel-stok-barang', [App\Http\Controllers\HomeController::class, 'getStokByJenisBarang'])->name('home.tabel-stok-barang');

Route::get('/home/grafik-jenis-kelamin-pedagang-by-jenis-produk', [App\Http\Controllers\HomeController::class, 'showGrafikJenisKelaminPedagangByJenisProduk'])->name('home.grafik-jenis-kelamin-pedagang-by-jenis-produk');

app/Models/Konsumen.php
<?php
/**
 * Created by PhpStorm.
 * User: rizky
 * Date: 09/09/2021
 * Time: 16:28
 */

namespace App\Models;

use Illuminate\Database\Eloquent\Model;
use Illuminate\Database\Eloquent\SoftDeletes;

class Konsumen extends Model
{
    use SoftDeletes;

    protected $table = 'konsumen';

    protected $fillable = [
        'kode_konsumen',
        'nama_konsumen',
        'user_create',
        'user_update',
        'user_delete',
    ];
}

app/Http/Controllers/KonsumenController.php
<?php
/**
 * Created by PhpStorm.
 * User: rizki
 * Date: 31/08/2021
 * Time: 5:04
 */

namespace App\Http\Controllers;

use Illuminate\Http\Request;
use App\Models\Konsumen;

class KonsumenController extends Controller
{
    function __construct()
    {
        $this->middleware('auth');
    }

    public function index()
    {
        $konsumen = Konsumen::all();
        return view('konsumen.index', [
            'konsumen' => $konsumen
        ]);
    }

    public function create()
    {
        return view('konsumen.create');
    }

    public function store(Request $request)
    {
        $request->validate([
            'nama_konsumen' => 'required|unique:konsumen,nama_konsumen',
        ]);

        $array = $request->only([
            'nama_konsumen'
        ]);
        $kode_konsumen = kode_hash();

        $array['kode_konsumen'] = $kode_konsumen;
        $array['user_create'] = $request->user()->id;

        $konsumen = Konsumen::create($array);

        return redirect()->route('konsumen.index')
            ->with('success_message', 'Berhasil menambah konsumen baru.');
    }

    public function show($id)
    {
        //
    }

    public function edit($id)
    {
        $konsumen = Konsumen::find($id);

        if (!$konsumen) return redirect()->route('konsumen.index')
            ->with('error_message', 'Konsumen dengan ID: '.$id.' tidak ditemukan.');

        return view('konsumen.edit', [
            'konsumen' => $konsumen
        ]);
    }

    public function update(Request $request, $id)
    {
        $request->validate([
            'nama_konsumen' => 'required|unique:konsumen,nama_konsumen,'.$id,
        ]);

        $konsumen = Konsumen::find($id);

        $konsumen->nama_konsumen = $request->nama_konsumen;
        $konsumen->user_update = $request->user()->id;

        $konsumen->save();

        return redirect()->route('konsumen.index')
            ->with('success_message', 'Berhasil mengubah konsumen.');
    }

    public function destroy(Request $request, $id)
    {
        $konsumen = Konsumen::find($id);

        if ($konsumen) {
            $konsumen->user_delete = $request->user()->id;

            $konsumen->save();

            $konsumen->delete();
        }

        return redirect()->route('konsumen.index')
            ->with('success_message', 'Berhasil menghapus konsumen.');
    }
}

resources/views/konsumen/create.blade.php
<?php
/**
 * Created by PhpStorm.
 * User: rizki
 * Date: 31/08/2021
 * Time: 5:07
 */

$title = 'Tambah Konsumen';

?>

@extends('adminlte::page')

@section('title', $title)

@section('content_header')
    <h1 class="m-0 text-dark">{{ $title }}</h1>
@stop

@section('content')
    @include('layouts/flash-message')

    <form action="{{route('konsumen.store')}}" method="post">
        @csrf
        @include('konsumen/form')
    </form>
@stop

resources/views/konsumen/edit.blade.php
<?php
/**
 * Created by PhpStorm.
 * User: rizky
 * Date: 09/09/2021
 * Time: 16:45
 */

$title = 'Edit Konsumen';

?>

@extends('adminlte::page')

@section('title', $title)

@section('content_header')
    <h1 class="m-0 text-dark">{{ $title }}</h1>
@stop

@section('content')
    @include('layouts/flash-message')

    <form action="{{route('konsumen.update', $konsumen)}}" method="post">
        @method('PUT')
        @csrf
        @include('konsumen/form');
    </form>
@stop

resources/views/konsumen/form.blade.php
<?php
/**
 * Created by PhpStorm.
 * User: rizky
 * Date: 09/09/2021
 * Time: 16:38
 */

?>

<div class="row">
    <div class="col-12">
        <div class="card">
            <div class="card-body">
                <div class="form-group">
                    <label for="nama_konsumen">Konsumen</label>
                    <input type="text" class="form-control @error('nama_konsumen') is-invalid @enderror" id="nama_konsumen" placeholder="Nama konsumen" name="nama_konsumen" value="{{ isset($konsumen)? $konsumen->nama_konsumen : old('nama_konsumen') }}" required>
                    @error('nama_konsumen') <span class="text-danger">{{$message}}</span> @enderror
                </div>
            </div>

            <div class="card-footer">
                {!! button_save() !!}
                {!! button_cancel('konsumen') !!}
            </div>
        </div>
    </div>
</div>

resources/views/konsumen/index.blade.php
<?php
/**
 * Created by PhpStorm.
 * User: rizki
 * Date: 31/08/2021
 * Time: 5:05
 */

$title = 'Pengelolaan Data Konsumen';

?>

@extends('adminlte::page')

@section('title', $title)

@section('content_header')
    <h1 class="m-0 text-dark">{{ $title }}</h1>
@stop

@section('content')
    @include('layouts/flash-message')

    <div class="row">
        <div class="col-12">
            <div class="card">
                <div class="card-header">
                    {!! button_add('konsumen') !!}
                </div>
                <div class="card-body">
                    <table class="table table-hover table-bordered table-stripped" id="simpleDatatable">
                        <thead>
                        <tr>
                            <th>No.</th>
                            <th>Konsumen</th>
                            <th class="text-center">Opsi</th>
                        </tr>
                        </thead>
                        <tbody>
                        @foreach($konsumen as $key => $row)
                            <tr>
                                <td>{{$key+1}}</td>
                                <td>{{$row->nama_konsumen}}</td>
                                <td class="text-center">
                                    {!! button_edit('konsumen', $row) !!}
                                    {!! button_delete('konsumen', $row) !!}
                                </td>
                            </tr>
                        @endforeach
                        </tbody>
                    </table>
                </div>
            </div>
        </div>
    </div>
@stop

@push('js')
    @include('layouts/js')
@endpush